export type AchievementName = 'Keep Your Account Safe!'
  | 'Bigger & Better'
  | 'Discover New Troops'
  | 'Bigger Coffers'
  | 'Gold Grab'
  | 'Elixir Escapade'
  | 'Heroic Heist'
  | 'Well Seasoned'
  | 'Nice and Tidy'
  | 'Empire Builder'
  | 'Clan War Wealth'
  | 'Friend in Need'
  | 'Sharing is caring'
  | 'Siege Sharer'
  | 'War Hero'
  | 'War League Legend'
  | 'Games Champion'
  | 'Unbreakable'
  | 'Sweet Victory!'
  | 'Conqueror'
  | 'League All-Star'
  | 'Humiliator'
  | 'Not So Easy This Time'
  | 'Union Buster'
  | 'Bust This!'
  | 'Wall Buster'
  | 'Mortar Mauler'
  | 'X-Bow Exterminator'
  | 'Firefighter'
  | 'Anti-Artillery'
  | 'Shattered and Scattered'
  | 'Counterspell'
  | 'Monolith Masher'
  | 'Multi-Archer Tower Terminator'
  | 'Ricochet Cannon Crusher'
  | 'Firespitter Finisher'
  | 'Multi-Gear Tower Trampler'
  | 'Crafter\'s Nightmare'
  | 'Get those Goblins!'
  | 'Supercharger'
  | 'Crafting Connoisseur'
  | 'Get those other Goblins!'
  | 'Get even more Goblins!'
  | 'Dragon Slayer'
  | 'Ungrateful Child'
  | 'Superb Work'
  | 'Master Engineering'
  | 'Hidden Treasures'
  | 'High Gear'
  | 'Next Generation Model'
  | 'Un-Build It'
  | 'Champion Builder'
  | 'Aggressive Capitalism'
  | 'Most Valuable Clanmate'
