export type ArmyLinkUnitName = 'Barbarian'
  | 'Archer'
  | 'Goblin'
  | 'Giant'
  | 'Wall Breaker'
  | 'Balloon'
  | 'Wizard'
  | 'Healer'
  | 'Dragon'
  | 'P.E.K.K.A'
  | 'Minion'
  | 'Hog Rider'
  | 'Valkyrie'
  | 'Golem'
  | 'Witch'
  | 'Lava Hound'
  | 'Bowler'
  | 'Baby Dragon'
  | 'Miner'
  | 'Super Barbarian'
  | 'Super Archer'
  | 'Super Wall Breaker'
  | 'Super Giant'
  | 'Yeti'
  | 'Sneaky Goblin'
  | 'Super Miner'
  | 'Rocket Balloon'
  | 'Ice Golem'
  | 'Electro Dragon'
  | 'Inferno Dragon'
  | 'Super Valkyrie'
  | 'Dragon Rider'
  | 'Super Witch'
  | 'Ice Hound'
  | 'Super Bowler'
  | 'Super Dragon'
  | 'Headhunter'
  | 'Super Wizard'
  | 'Super Minion'
  | 'Electro Titan'
  | 'Apprentice Warden'
  | 'Super Hog'
  | 'Root Rider'
  | 'Druid'
  | 'Thrower'
  | 'Super Yeti'
  | 'Furnace'
  | 'Ice Wizard'
  | 'Battle Ram'
  | 'Royal Ghost'
  | 'Pumpkin Barbarian'
  | 'Giant Skeleton'
  | 'Skeleton Barrel'
  | 'El Primo'
  | 'Party Wizard'
  | 'Firecracker'
  | 'Azure Dragon'
  | 'Snake Barrel'
  | 'Wall Wrecker'
  | 'Battle Blimp'
  | 'Stone Slammer'
  | 'Siege Barracks'
  | 'Log Launcher'
  | 'Flame Flinger'
  | 'Battle Drill'
  | 'Troop Launcher'
