export type ArmyLinkEquipmentName = 'Barbarian Puppet'
  | 'Rage Vial'
  | 'Archer Puppet'
  | 'Invisibility Vial'
  | 'Eternal Tome'
  | 'Life Gem'
  | 'Seeking Shield'
  | 'Royal Gem'
  | 'Earthquake Boots'
  | 'Giant Gauntlet'
  | 'Vampstache'
  | 'Giant Arrow'
  | 'Healer Puppet'
  | 'Fireball'
  | 'Rage Gem'
  | 'Healing Tome'
  | 'Dark Crown'
  | 'Henchment Puppet'
  | 'Dark Orb'
  | 'Metal Pants'
  | 'Noble Iron'
