export type ArmyLinkSpellName = 'Lightning Spell'
  | 'Healing Spell'
  | 'Rage Spell'
  | 'Jump Spell'
  | 'Freeze Spell'
  | 'Clone Spell'
  | 'Invisibility Spell'
  | 'Recall Spell'
  | 'Poison Spell'
  | 'Earthquake Spell'
  | 'Haste Spell'
  | 'Skeleton Spell'
  | 'Bat Spell'
  | 'Overgrowth Spell'
  | 'Revive Spell'
  | 'Santa\'s Surprise'
  | 'Birthday Boom'
