export type EquipmentName = 'Barbarian Puppet'
  | 'Earthquake Boots'
  | 'Rage Vial'
  | 'Vampstache'
  | 'Giant Gauntlet'
  | 'Spiky Ball'
  | 'Archer Puppet'
  | 'Invisibility Vial'
  | 'Giant Arrow'
  | 'Healer Puppet'
  | 'Frozen Arrow'
  | 'Eternal Tome'
  | 'Life Gem'
  | 'Rage Gem'
  | 'Healing Tome'
  | 'Fireball'
  | 'Royal Gem'
  | 'Seeking Shield'
  | 'Hog Rider Puppet'
  | 'Haste Vial'
