export type LabelName = 'Clan Wars'
  | 'Clan War League'
  | 'Trophy Pushing'
  | 'Friendly Wars'
  | 'Clan Games'
  | 'Builder Base'
  | 'Base Designing'
  | 'Farming'
  | 'Active Donator'
  | 'Clan Capital'
  | 'Active Daily'
  | 'Hungry Learner'
  | 'Friendly'
  | 'Talkative'
  | 'Teacher'
  | 'Competitive'
  | 'Veteran'
  | 'Newbie'
  | 'Amateur Attacker'
