export type SuperTroopName = 'Super Barbarian'
  | 'Super Archer'
  | 'Super Giant'
  | 'Sneaky Goblin'
  | 'Super Wall Breaker'
  | 'Rocket Balloon'
  | 'Super Wizard'
  | 'Super Dragon'
  | 'Inferno Dragon'
  | 'Super Miner'
  | 'Super Minion'
  | 'Super Hog Rider'
  | 'Super Valkyrie'
  | 'Super Witch'
  | 'Ice Hound'
  | 'Super Bowler'
