export type TroopName = 'Barbarian'
  | 'Archer'
  | 'Giant'
  | 'Goblin'
  | 'Wall Breaker'
  | 'Balloon'
  | 'Wizard'
  | 'Healer'
  | 'Dragon'
  | 'P.E.K.K.A'
  | 'Baby Dragon'
  | 'Miner'
  | 'Electro Dragon'
  | 'Yeti'
  | 'Dragon Rider'
  | 'Electro Titan'
  | 'Root Rider'
  | 'Thrower'
  | 'Minion'
  | 'Hog Rider'
  | 'Valkyrie'
  | 'Golem'
  | 'Witch'
  | 'Lava Hound'
  | 'Bowler'
  | 'Ice Golem'
  | 'Headhunter'
  | 'Apprentice Warden'
  | 'Druid'
  | 'Furnace'
  | 'Raged Barbarian'
  | 'Sneaky Archer'
  | 'Boxer Giant'
  | 'Beta Minion'
  | 'Bomber'
  | 'Baby Dragon'
  | 'Cannon Cart'
  | 'Night Witch'
  | 'Drop Ship'
  | 'Power P.E.K.K.A'
  | 'Hog Glider'
  | 'Electrofire Wizard'
