export type WarLeagueName = 'Bronze III'
  | 'Bronze II'
  | 'Bronze I'
  | 'Silver III'
  | 'Silver II'
  | 'Silver I'
  | 'Gold III'
  | 'Gold II'
  | 'Gold I'
  | 'Crystal III'
  | 'Crystal II'
  | 'Crystal I'
  | 'Master III'
  | 'Master II'
  | 'Master I'
  | 'Champion III'
  | 'Champion II'
  | 'Champion I'
